### ISSUE TITLE
support for python 2.7 and 3.4?

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [MagicStack/contextvars#1]
hi, i was just evaluating this package as means to generalize some older unfortunate code into something nicer

unfortunately i have to support python 2.7 and 3.4 for a while longer

**Comment by 1st1** [comment]
This isn't likely to happen, sorry.  All target users for contextvars are Python 3.5+, and I'm not interested in doing work to support Python 2.7 :(

**Comment by RonnyPfannschmidt** [comment]
thanks for the update/clarification
