### ISSUE TITLE
Use immutables

### ISSUE THREAD

**Issue by fantix** [MagicStack/contextvars#3]
As I can see project immutables was created after project contextvars, so I guess you haven't got time to make contextvars use immutables. If that's expected, I may be able to help with that.

**Comment by vltr** [comment]
Are not both projects from MagicStack?



Em sáb, 28 de abr de 2018 07:29, Fantix King <notifications@github.com>
escreveu:

**Comment by fantix** [comment]
@vltr Yes they are. Current contextvars backport is using Python `dict`, not the boosted `immutables.Map`.

**Comment by vltr** [comment]
Yeah, I think it must be on plans. I'm already using immutables :-)



Em sáb, 28 de abr de 2018 07:57, Fantix King <notifications@github.com>
escreveu:

**Comment by fantix** [comment]
I think so too. 😈 That's why I'm creating this issue to confirm.

**Comment by 1st1** [comment]
Yes, I didn't have time to update this package to use immutables. Feel free to submit a PR!
